import type { Metadata } from "next";
import { Bebas_Neue, Inter, Manrope } from "next/font/google";
import "./globals.css";


const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400"
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],  
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${inter.variable} ${manrope.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
